apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/rsksandaruwan32/ci-cd-final-project"
        - name: revision
          value: "main"
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: tests
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace