apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: Cleanup the workspace
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        rm -rf $(workspaces.source.path)/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  description: Run unit tests with nose
  workspaces:
    - name: source
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        nosetests -v --with-spec --spec-color --with-coverage --cover-package=service